"""Version 0.0

Revision ID: 7159f88f9452
Revises: 
Create Date: 2026-05-07 02:54:50.492411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7159f88f9452'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_offline_iran',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_name', sa.String(length=80), nullable=False),
    sa.Column('experience_text', sa.String(length=490), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_offline_iran')
    # ### end Alembic commands ###
