"""Version 0.2

Revision ID: fcf9a929b5ac
Revises: 23f204e9d2a4
Create Date: 2026-05-08 20:32:30.911553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf9a929b5ac'
down_revision: Union[str, Sequence[str], None] = '23f204e9d2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience_offline_iran', 'sender_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('experience_offline_iran', 'experience_text',
               existing_type=sa.VARCHAR(length=490),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experience_offline_iran', 'experience_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=490),
               existing_nullable=False)
    op.alter_column('experience_offline_iran', 'sender_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
